### ISSUE TITLE
Modificar barra lateral izquierda

### ISSUE THREAD

**Issue by oacastillol** [Usimte/usimte.github.io#5]
En varias pantallas es incomodo para leer el contenido pues se solapa con las letras y dificulta leer.
![captura de pantalla_2017-01-20_23-17-39](https://cloud.githubusercontent.com/assets/11141363/22171893/e22b1518-df66-11e6-801f-0b6baf986f75.png)

Además no entiendo ¿Qué función cumple?

**Comment by jonatan360** [comment]
Ok, ya la quite.
